[package]
name = "myapp"
version = "0.1.0"
edition = "2018"

[dependencies]
coap = "0.12.0"
coap-lite = "0.9.1"
tokio = { version = "1.14.0", features = ["full"] }

[build-dependencies]
tokio = { version = "1.14.0", features = ["full"] }

[[bin]]
name = "coap-server"
path = "src/main.rs"
